<a href="https://colab.research.google.com/github/Hj-lh/AI-Powered-Arabic-Chatbot-with-NLP/blob/main/DeepLearning_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
2+2

4

In [2]:
import torch
import numpy as np

In [3]:
n = np.random.randn(2,3)
print(n)

t = torch.randn(2,3)

print(t)

[[ 1.43393411 -0.95832165  0.04156187]
 [ 0.87490143  1.09275681  0.07244518]]
tensor([[-0.3025, -0.1196, -0.2670],
        [ 0.9322, -0.8495, -1.0356]])


In [5]:
t3 = torch.zeros(2,3,4)
print(t3)
torch.arange(10)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
resh=t.reshape(3,-1)#-1 if we don't know the number of item
print(resh)

tensor([[-0.3025, -0.1196],
        [-0.2670,  0.9322],
        [-0.8495, -1.0356]])
